### ISSUE TITLE
Small bug in visualization code

### ISSUE THREAD

**Issue by abhisheknaik96** [deepmind/csuite#4]
Image.new() requires size=(width, height) [[source](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.new)] but [taxi.py#L342](https://github.com/deepmind/csuite/blob/main/csuite/environments/taxi.py#L342) calls it with (height, width). It still works because the taxi environment is a square, but in rectangular environments like catch we'll need to use (width, height).

**Comment by szepi1991** [comment]
Thanks for reporting this. I agree that even though it doesn't matter in that particular environment this should be updated.

**Comment by kevroi** [comment]
May I fork and submit a pull request to change this minor bug?

**Comment by kevroi** [comment]
May I submit a pull req for this minor bug fix? :)

**Comment by szepi1991** [comment]
Yes of course, your contribution would be appreciated :)
